version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
          working_directory: Backend
      - run:
          name: Run tests
          command: npm test
          working_directory: Backend

  start_sonarqube:
    docker:
      - image: circleci/node:14
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Start SonarQube
          command: |
            docker run -d --name sonarqube -p 9000:9000 sonarqube:latest
      - run:
          name: Wait for SonarQube to be ready
          command: |
            echo "Waiting for SonarQube to start..."
            until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do
              sleep 5
            done
            echo "SonarQube is up and running."

  sonar_analysis:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install SonarQube Scanner
          command: npm install -g sonarqube-scanner
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.sources=Backend \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=$SONAR_TOKEN

  stop_sonarqube:
    docker:
      - image: circleci/node:14
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Stop SonarQube
          command: docker stop sonarqube
      - run:
          name: Remove SonarQube container
          command: docker rm sonarqube

  build_docker_image:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: docker build -t hxrm/apdsp3:latest -f Backend/MyDockerfile Backend
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u hxrm --password-stdin
      - run:
          name: Push Docker image
          command: docker push hxrm/apdsp3:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_test
      - start_sonarqube
      - sonar_analysis:
          requires:
            - build_test
            - start_sonarqube
      - stop_sonarqube:
          requires:
            - sonar_analysis
      - build_docker_image:
          requires:
            - sonar_analysis
