#the issue is because it doesnt find the sonarqube
version: 2.1

orbs:
  sonarscanner: psl/sonarscanner@0.0.4

jobs:
  build_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
          working_directory: Backend
      - run:
          name: Run tests
          command: npm test
          working_directory: Backend

  sonarqube_scan:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: /tmp/workspace
    environment:
      ENV_FILE: /tmp/workspace/.circleenv
      DOCKER_BUILDKIT: "1"
      BUILDKIT_PROGRESS: plain
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start SonarQube
          command: |
            docker run -d --name sonarqube -p 9000:9000 sonarqube:latest
      - run:
          name: Wait for SonarQube to be ready
          command: |
            echo "Waiting for SonarQube to start..."
            retries=0
            max_retries=60  # Increase the number of retries to allow more time for SonarQube to start
            while ! curl -s http://localhost:9000/api/system/status | grep -q "\"status\":\"UP\""; do
              retries=$((retries + 1))
              if [ $retries -ge $max_retries ]; then
                echo "SonarQube did not start in time."
                docker logs sonarqube  # Print SonarQube logs for debugging
                exit 1
              fi
              sleep 10
            done
            echo "SonarQube is up and running."
      - run:
          name: Install SonarQube Scanner
          command: |
            wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner.zip
            rm sonar-scanner.zip
      - run:
          name: Run SonarScanner
          command: |
            export PATH="$PATH:$PWD/sonar-scanner-4.6.2.2472-linux/bin"
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=$SONARQUBE_TOKEN \
              -Dsonar.sources="Backend"

  build_docker_image:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: docker build -t hxrm/apdsp3:latest -f Backend/MyDockerfile Backend
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u hxrm --password-stdin
      - run:
          name: Push Docker image
          command: docker push hxrm/apdsp3:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_test
      - sonarqube_scan:
          requires:
            - build_test
      - build_docker_image:
          requires:
            - sonarqube_scan
