version: 2.1
#public orb so had to change security
orbs:
  sonarscanner: psl/sonarscanner@0.0.4

jobs:
  build_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
          working_directory: Backend
      - run:
          name: Run tests
          command: npm test
          working_directory: Backend

  build_docker_image:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: docker build -t hxrm/apdsp3:latest -f Backend/MyDockerfile Backend
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u hxrm --password-stdin
      - run:
          name: Push Docker image
          command: docker push hxrm/apdsp3:latest

workflows:
  build_and_deploy:
    jobs:
      - build_test
      - sonarscanner/scan:
          requires:
            - build_test
          context: sonarqube
          sonar-url: $SONAR_HOST_URL
          sonar-login: $SONARQUBE_TOKEN
          sonar-project-key: $SONAR_PROJECT_KEY
          sonar-sources: Backend
      - build_docker_image:
          requires:
            - sonarscanner/scan
