version: 2.1

# Define reusable jobs for your workflow
jobs:
  build_test:
    docker:
      - image: circleci/node:14  # Use a Node.js image suitable for your project
    steps:
      - checkout  # Check out your project repository
      - run:
          name: Install npm dependencies
          command: npm install
          working_directory: Backend  # Change to your specific project folder
      - run:
          name: Run tests
          command: npm test
          working_directory: Backend

  # Job for running SonarQube scan using the SonarScanner CLI
  sonarqube_scan:
    docker:
      - image: hxrm/sonar-scanner-cli:4.6-jdk17  # Custom Docker image with Java 17, Node.js, and SonarScanner
    steps:
      - checkout
      - run:
          name: Run SonarScanner
          command: |
            echo "Project Key: $SONAR_PROJECT_KEY"
            sonar-scanner -X \
              -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="${CIRCLE_BRANCH}" \
              -Dproject.settings=Backend/sonar-project.properties

# Define the workflow that runs these jobs in order
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_test
      - sonarqube_scan:
          requires:
            - build_test  # Only run SonarQube scan after tests pass
