name: CI

on:
  push:
    branches:
      - dev-main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Navigate to Backend directory
        run: cd Backend

      - name: Install dependencies
        run: npm install
        working-directory: Backend

      # Step 1: Give execute permissions to ESLint binary
      - name: Give execute permission to ESLint
        run: sudo chmod +x ./node_modules/.bin/eslint
        working-directory: Backend

      # Step 2: Run Linting with elevated permissions
      - name: Run ESLint
        run: npm run lint
        working-directory: Backend
      
      # Step 3: Run Tests with elevated permissions
      - name: Run tests with elevated permissions
        run: |
          sudo chmod -R 755 ./node_modules
          npm test
        working-directory: Backend

  zap:
    runs-on: ubuntu-latest
    needs: test  # This ensures ZAP runs after the tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 1: Start the backend server
      - name: Start Backend server
        run: |
          npm install
          npm start &
        working-directory: Backend

      # Step 2: Start the frontend server
      - name: Start Frontend server
        run: |
          npm start &
        working-directory: Frontend

      # Step 3: Wait for the apps to be ready
      - name: Wait for the apps to be ready
        run: sleep 2

      # Step 4: Install OWASP ZAP
      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy

      # Step 5: Run OWASP ZAP for the frontend
      - name: Run OWASP ZAP on Frontend
        run: |
          zap-baseline.py -t http://localhost:3000 -r zap_report_frontend.html

      # Step 6: Run OWASP ZAP for the backend
      - name: Run OWASP ZAP on Backend
        run: |
          zap-baseline.py -t https://localhost:5050 -r zap_report_backend.html -I  # `-I` flag to ignore SSL warnings (for self-signed certificates)

      # Step 7: Upload ZAP reports for both frontend and backend
      - name: Upload Frontend ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report-frontend
          path: zap_report_frontend.html

      - name: Upload Backend ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report-backend
          path: zap_report_backend.html
